name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: raniakashkash05/location-microservice

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

    - name: Make gradlew executable
      run: chmod +x gradlew
      working-directory: ./path/to/your/microservice  # غير هذا للمسار الصحيح

    - name: Build with Gradle Wrapper
      run: ./gradlew build -x test
      working-directory: ./path/to/your/microservice  # غير هذا للمسار الصحيح

    - name: Create Dockerfile
      run: |
        cat > Dockerfile << 'EOF'
        FROM eclipse-temurin:17-jre-alpine
        WORKDIR /app
        COPY build/libs/*.jar app.jar
        EXPOSE 8080
        ENTRYPOINT ["java", "-jar", "app.jar"]
        EOF
      working-directory: ./path/to/your/microservice  # غير هذا للمسار الصحيح

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./path/to/your/microservice  # غير هذا للمسار الصحيح
        file: ./path/to/your/microservice/Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        annotations: ${{ steps.meta.outputs.annotations }}
        push: true

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582
      with:
        build-root-directory: ./path/to/your/microservice  # غير هذا للمسار الصحيح
ndency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
